name: upload site to aliyun
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: compile source code
      run: npm run build

    - name: publish
      run: |
        npm run publish